root: true
env:
  browser: true
  es2020: true

overrides:
  - files: "*.ts"
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@angular-eslint/recommended
      - plugin:@angular-eslint/template/process-inline-templates
      - prettier
    parserOptions:
      project:
        - tsconfig.app.json
        - tsconfig.spec.json
      createDefaultProgram: true
    rules:
      "@angular-eslint/directive-selector":
        - error
        - type: attribute
          style: camelCase
      "@angular-eslint/component-selector":
        - error
        - type: element
          style: kebab-case
      no-template-curly-in-string:
        - warn
      "@typescript-eslint/no-unused-vars":
        - warn
        - ignoreRestSiblings: true
          args: after-used

  - files: "*.html"
    extends: plugin:@angular-eslint/template/recommended
